name: Update Weather Data

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; else pip install requests pandas; fi

      - name: Update weather data
        run: |
          cd backend
          python fetch_weather_data.py

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Commit and push if changed
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add backend/data/processed_*.json frontend/public/backend/data/processed_*.json
          git diff --staged --quiet || git commit -m "Auto-update weather data $(TZ='Europe/Paris' date +%Y-%m-%d-%H:%M)"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
